# Generated by Django 4.2.14 on 2024-08-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['submissao__evento', '-media_final_avaliacao', 'submissao__responsavel__nome']},
        ),
    ]
