# Generated by Django 4.2.14 on 2024-08-26 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_alter_avaliacao_merito_relevancia_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='media_final_avaliacao',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5)], verbose_name='Média Final'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_clareza_convidado',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Clareza e organização: O artigo apresenta escrita clara, organizada e coerente?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_clareza_responsavel',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Clareza e organização: O artigo apresenta escrita clara, organizada e coerente?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_clareza_suplente',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Clareza e organização: O artigo apresenta escrita clara, organizada e coerente?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_conclusao_convidado',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Conclusões: O trabalho traz considerações finais ou conclusão, apresentando reflexões,  avanços ou soluções ao tema abordado, conforme os objetivos propostos?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_conclusao_responsavel',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Conclusões: O trabalho traz considerações finais ou conclusão, apresentando reflexões,  avanços ou soluções ao tema abordado, conforme os objetivos propostos?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_conclusao_suplente',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Conclusões: O trabalho traz considerações finais ou conclusão, apresentando reflexões,  avanços ou soluções ao tema abordado, conforme os objetivos propostos?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_contribuicao_convidado',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Contribuição: O trabalho apresenta contribuição para a área em que foi submetido ao evento?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_contribuicao_responsavel',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Contribuição: O trabalho apresenta contribuição para a área em que foi submetido ao evento?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_contribuicao_suplente',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Contribuição: O trabalho apresenta contribuição para a área em que foi submetido ao evento?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_fundamentacao_convidado',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Fundamentação teórica: O artigo baseia-se em teorias, fundamentos e conceitos relevantes na área em que foi submetido ao evento?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_fundamentacao_responsavel',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Fundamentação teórica: O artigo baseia-se em teorias, fundamentos e conceitos relevantes na área em que foi submetido ao evento?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_fundamentacao_suplente',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Fundamentação teórica: O artigo baseia-se em teorias, fundamentos e conceitos relevantes na área em que foi submetido ao evento?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_metodologia_convidado',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Metodologia: O artigo apresenta uma metodologia e a utiliza de forma apropriada para o problema proposto?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_metodologia_responsavel',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Metodologia: O artigo apresenta uma metodologia e a utiliza de forma apropriada para o problema proposto?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_metodologia_suplente',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Metodologia: O artigo apresenta uma metodologia e a utiliza de forma apropriada para o problema proposto?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_referencias_convidado',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Referências bibliográficas: As referências utilizadas no artigo são atualizadas e/ou relevantes? '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_referencias_responsavel',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Referências bibliográficas: As referências utilizadas no artigo são atualizadas e/ou relevantes? '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_referencias_suplente',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Referências bibliográficas: As referências utilizadas no artigo são atualizadas e/ou relevantes? '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_relevancia_convidado',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Relevância: O artigo aborda um problema atual e/ou relevante na área em que foi submetido ao evento?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_relevancia_responsavel',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Relevância: O artigo aborda um problema atual e/ou relevante na área em que foi submetido ao evento?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_relevancia_suplente',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Relevância: O artigo aborda um problema atual e/ou relevante na área em que foi submetido ao evento?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_resultados_convidado',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Resultados e discussões: Os resultados são apresentados e discutidos adequadamente?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_resultados_responsavel',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Resultados e discussões: Os resultados são apresentados e discutidos adequadamente?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_resultados_suplente',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='De 1 a 5. Nota 1 equivale a NÃO atende, enquanto, nota 5 atende COMPLETAMENTE.', max_length=1, null=True, verbose_name='Resultados e discussões: Os resultados são apresentados e discutidos adequadamente?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota_final_convidado',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5)], verbose_name='Final Avaliador 3'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota_final_responsavel',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5)], verbose_name='Final Avaliador 1'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota_final_suplente',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5)], verbose_name='Final Avaliador 2'),
        ),
    ]
