# Generated by Django 4.2.16 on 2024-10-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0007_alter_avaliacao_nota_final_suplente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='parecer_avaliador_convidado',
            field=models.TextField(blank=True, help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=10000, null=True, verbose_name='Parecer do avaliador 3 (10000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='parecer_avaliador_responsavel',
            field=models.TextField(blank=True, help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=10000, null=True, verbose_name='Parecer do avaliador 1 (10000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='parecer_avaliador_suplente',
            field=models.TextField(blank=True, help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=10000, null=True, verbose_name='Parecer do avaliador 2 (10000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='parecer_reavaliacao_avaliador_convidado',
            field=models.TextField(blank=True, help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=10000, null=True, verbose_name='Parecer de REAVALIAÇÃO do avaliador 3 (10000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='parecer_reavaliacao_avaliador_responsavel',
            field=models.TextField(blank=True, help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=10000, null=True, verbose_name='Parecer de REAVALIAÇÃO do avaliador 1 (10000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='parecer_reavaliacao_avaliador_suplente',
            field=models.TextField(blank=True, help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=10000, null=True, verbose_name='Parecer de REAVALIAÇÃO do avaliador 2 (10000 caracteres)'),
        ),
    ]
