# Generated by Django 4.2.14 on 2024-10-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_alter_evento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_divulgacao_trabalhos_aprovados',
            field=models.DateField(help_text='Use dd/mm/aaaa', max_length=10, null=True, verbose_name='Data de divulgação dos trabalhos aprovados *'),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_limite_reenvio_trabalhos_corrigidos',
            field=models.DateField(help_text='Use dd/mm/aaaa', max_length=10, null=True, verbose_name='Data de reenvio de trabalhos aprovados e corrigidos *'),
        ),
        migrations.AddField(
            model_name='evento',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Se marcada a caixa, os resultados das avaliações serão exibidas aos autores de trabalhos', verbose_name='Resultados publicados'),
        ),
    ]
