# Generated by Django 4.2.16 on 2024-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_alter_evento_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Se marcada a caixa, os resultados das avaliações serão exibidos aos autores de trabalhos', verbose_name='PUBLICAR RESULTADOS APÓS AVALIAÇÕES?'),
        ),
    ]
