# Generated by Django 4.2.14 on 2024-08-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0005_alter_submissao_abstract_alter_submissao_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='abstract',
            field=models.TextField(help_text='Máximo caracteres: 1200. Se for colar texto de outro aplicativo, certifique-se que o abstract esteja completo', max_length=1200, verbose_name='Abstract *'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='resumo',
            field=models.TextField(help_text='Máximo caracteres: 1200. Se for colar texto de outro aplicativo, certifique-se que o resumo esteja completo', max_length=1200, verbose_name='Resumo *'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='titulo',
            field=models.CharField(help_text='Se for colar texto de outro aplicativo, certifique-se que o título esteja completo', max_length=200, verbose_name='Título *'),
        ),
    ]
