# Generated by Django 4.2.14 on 2024-08-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0006_alter_submissao_abstract_alter_submissao_resumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='status',
            field=models.CharField(choices=[('EM EDICAO', 'Em edição'), ('EM AVALIACAO', 'Em avaliação'), ('EM CORRECAO', 'Em correção'), ('APROVADO', 'Aprovado'), ('RETIRADO PELO RESPONSAVEL', 'Retirado pelo responsável'), ('RETIRADO PELO COORDENADOR', 'Retirado pelo coordenador'), ('REPROVADO', 'Reprovado')], default='EM EDICAO', max_length=25, verbose_name='Status da submissão'),
        ),
    ]
