# Generated by Django 4.2.14 on 2024-10-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0007_alter_submissao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='arquivo_final',
            field=models.FileField(blank=True, help_text='Utilize arquivo .PDF e lembre de incluir dados dos autores', null=True, upload_to='midias', verbose_name='Arquivo PDF corrigido para a versão final'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='status',
            field=models.CharField(choices=[('EM EDICAO', 'Em edição'), ('EM AVALIACAO', 'Em avaliação'), ('EM CORRECAO', 'Em correção'), ('APROVADO', 'Aprovado'), ('RETIRADO PELO RESPONSAVEL', 'Retirado pelo responsável'), ('RETIRADO PELO COORDENADOR', 'Retirado pelo coordenador'), ('REPROVADO', 'Reprovado'), ('FINALIZADO', 'Finalizado')], default='EM EDICAO', max_length=25, verbose_name='Status da submissão'),
        ),
    ]
