# Generated by Django 4.2.16 on 2024-10-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0008_alter_submissao_arquivo_final_alter_submissao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='arquivo_final',
            field=models.FileField(blank=True, help_text='Utilize arquivo .DOCX e lembre de incluir dados dos autores', null=True, upload_to='midias', verbose_name='Arquivo corrigido para a versão final'),
        ),
    ]
