# Generated by Django 4.2.16 on 2024-10-23 14:35

import django.contrib.auth.models
from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_aceita_termo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('coordenadores', usuario.models.CoordenadorAtivoManager()),
                ('membros', usuario.models.MembroAtivoManager()),
                ('avaliadores', usuario.models.AvaliadorAtivoManager()),
                ('usuarios_ativos', usuario.models.UsuarioAtivoManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='eh_avaliador',
            field=models.BooleanField(default=False, help_text='Se marcado, o membro ou coordenador de evento aparece na lista de avaliadores para um evento', verbose_name='É um membro avaliador?'),
        ),
    ]
